package textfarming.datasources.market;

import java.util.HashMap;
import java.util.Map;

/**
 * A containing for mappings between country names and country codes, for use in the currency converter.
 *
 * @see CurrencyConverter
 * @author Benji
 */
public class CountryCodes {
    final static Map<String, String> countryCodes;
    static {
        countryCodes = new HashMap<>();
        countryCodes.put("Aruba", "ABW");
        countryCodes.put("Afghanistan", "AFG");
        countryCodes.put("Angola", "AGO");
        countryCodes.put("Anguilla", "AIA");
        countryCodes.put("Åland Islands", "ALA");
        countryCodes.put("Albania", "ALB");
        countryCodes.put("Andorra", "AND");
        countryCodes.put("United Arab Emirates", "ARE");
        countryCodes.put("Argentina", "ARG");
        countryCodes.put("Armenia", "ARM");
        countryCodes.put("American Samoa", "ASM");
        countryCodes.put("Antarctica", "ATA");
        countryCodes.put("French Southern Territories", "ATF");
        countryCodes.put("Antigua and Barbuda", "ATG");
        countryCodes.put("Australia", "AUS");
        countryCodes.put("Austria", "AUT");
        countryCodes.put("Azerbaijan", "AZE");
        countryCodes.put("Burundi", "BDI");
        countryCodes.put("Belgium", "BEL");
        countryCodes.put("Benin", "BEN");
        countryCodes.put("Bonaire, Sint Eustatius and Saba", "BES");
        countryCodes.put("Burkina Faso", "BFA");
        countryCodes.put("Bangladesh", "BGD");
        countryCodes.put("Bulgaria", "BGR");
        countryCodes.put("Bahrain", "BHR");
        countryCodes.put("Bahamas", "BHS");
        countryCodes.put("Bosnia and Herzegovina", "BIH");
        countryCodes.put("Saint Barthélemy", "BLM");
        countryCodes.put("Belarus", "BLR");
        countryCodes.put("Belize", "BLZ");
        countryCodes.put("Bermuda", "BMU");
        countryCodes.put("Bolivia (Plurinational State of)", "BOL");
        countryCodes.put("Brazil", "BRA");
        countryCodes.put("Barbados", "BRB");
        countryCodes.put("Brunei Darussalam", "BRN");
        countryCodes.put("Bhutan", "BTN");
        countryCodes.put("Bouvet Island", "BVT");
        countryCodes.put("Botswana", "BWA");
        countryCodes.put("Central African Republic", "CAF");
        countryCodes.put("Canada", "CAN");
        countryCodes.put("Cocos (Keeling) Islands", "CCK");
        countryCodes.put("Switzerland", "CHE");
        countryCodes.put("Chile", "CHL");
        countryCodes.put("China", "CHN");
        countryCodes.put("Côte d'Ivoire", "CIV");
        countryCodes.put("Cameroon", "CMR");
        countryCodes.put("Congo, Democratic Republic of the", "COD");
        countryCodes.put("Congo", "COG");
        countryCodes.put("Cook Islands", "COK");
        countryCodes.put("Colombia", "COL");
        countryCodes.put("Comoros", "COM");
        countryCodes.put("Cabo Verde", "CPV");
        countryCodes.put("Costa Rica", "CRI");
        countryCodes.put("Cuba", "CUB");
        countryCodes.put("Curaçao", "CUW");
        countryCodes.put("Christmas Island", "CXR");
        countryCodes.put("Cayman Islands", "CYM");
        countryCodes.put("Cyprus", "CYP");
        countryCodes.put("Czechia", "CZE");
        countryCodes.put("Germany", "DEU");
        countryCodes.put("Djibouti", "DJI");
        countryCodes.put("Dominica", "DMA");
        countryCodes.put("Denmark", "DNK");
        countryCodes.put("Dominican Republic", "DOM");
        countryCodes.put("Algeria", "DZA");
        countryCodes.put("Ecuador", "ECU");
        countryCodes.put("Egypt", "EGY");
        countryCodes.put("Eritrea", "ERI");
        countryCodes.put("Western Sahara", "ESH");
        countryCodes.put("Spain", "ESP");
        countryCodes.put("Estonia", "EST");
        countryCodes.put("Ethiopia", "ETH");
        countryCodes.put("Finland", "FIN");
        countryCodes.put("Fiji", "FJI");
        countryCodes.put("Falkland Islands (Malvinas)", "FLK");
        countryCodes.put("France", "FRA");
        countryCodes.put("Faroe Islands", "FRO");
        countryCodes.put("Micronesia (Federated States of)", "FSM");
        countryCodes.put("Gabon", "GAB");
        countryCodes.put("United Kingdom of Great Britain and Northern Ireland", "GBR");
        countryCodes.put("Georgia", "GEO");
        countryCodes.put("Guernsey", "GGY");
        countryCodes.put("Ghana", "GHA");
        countryCodes.put("Gibraltar", "GIB");
        countryCodes.put("Guinea", "GIN");
        countryCodes.put("Guadeloupe", "GLP");
        countryCodes.put("Gambia", "GMB");
        countryCodes.put("Guinea-Bissau", "GNB");
        countryCodes.put("Equatorial Guinea", "GNQ");
        countryCodes.put("Greece", "GRC");
        countryCodes.put("Grenada", "GRD");
        countryCodes.put("Greenland", "GRL");
        countryCodes.put("Guatemala", "GTM");
        countryCodes.put("French Guiana", "GUF");
        countryCodes.put("Guam", "GUM");
        countryCodes.put("Guyana", "GUY");
        countryCodes.put("Hong Kong", "HKG");
        countryCodes.put("Heard Island and McDonald Islands", "HMD");
        countryCodes.put("Honduras", "HND");
        countryCodes.put("Croatia", "HRV");
        countryCodes.put("Haiti", "HTI");
        countryCodes.put("Hungary", "HUN");
        countryCodes.put("Indonesia", "IDN");
        countryCodes.put("Isle of Man", "IMN");
        countryCodes.put("India", "IND");
        countryCodes.put("British Indian Ocean Territory", "IOT");
        countryCodes.put("Ireland", "IRL");
        countryCodes.put("Iran (Islamic Republic of)", "IRN");
        countryCodes.put("Iraq", "IRQ");
        countryCodes.put("Iceland", "ISL");
        countryCodes.put("Israel", "ISR");
        countryCodes.put("Italy", "ITA");
        countryCodes.put("Jamaica", "JAM");
        countryCodes.put("Jersey", "JEY");
        countryCodes.put("Jordan", "JOR");
        countryCodes.put("Japan", "JPN");
        countryCodes.put("Kazakhstan", "KAZ");
        countryCodes.put("Kenya", "KEN");
        countryCodes.put("Kyrgyzstan", "KGZ");
        countryCodes.put("Cambodia", "KHM");
        countryCodes.put("Kiribati", "KIR");
        countryCodes.put("Saint Kitts and Nevis", "KNA");
        countryCodes.put("Korea, Republic of", "KOR");
        countryCodes.put("Kuwait", "KWT");
        countryCodes.put("Lao People's Democratic Republic", "LAO");
        countryCodes.put("Lebanon", "LBN");
        countryCodes.put("Liberia", "LBR");
        countryCodes.put("Libya", "LBY");
        countryCodes.put("Saint Lucia", "LCA");
        countryCodes.put("Liechtenstein", "LIE");
        countryCodes.put("Sri Lanka", "LKA");
        countryCodes.put("Lesotho", "LSO");
        countryCodes.put("Lithuania", "LTU");
        countryCodes.put("Luxembourg", "LUX");
        countryCodes.put("Latvia", "LVA");
        countryCodes.put("Macao", "MAC");
        countryCodes.put("Saint Martin (French part)", "MAF");
        countryCodes.put("Morocco", "MAR");
        countryCodes.put("Monaco", "MCO");
        countryCodes.put("Moldova, Republic of", "MDA");
        countryCodes.put("Madagascar", "MDG");
        countryCodes.put("Maldives", "MDV");
        countryCodes.put("Mexico", "MEX");
        countryCodes.put("Marshall Islands", "MHL");
        countryCodes.put("Macedonia, the former Yugoslav Republic of", "MKD");
        countryCodes.put("Mali", "MLI");
        countryCodes.put("Malta", "MLT");
        countryCodes.put("Myanmar", "MMR");
        countryCodes.put("Montenegro", "MNE");
        countryCodes.put("Mongolia", "MNG");
        countryCodes.put("Northern Mariana Islands", "MNP");
        countryCodes.put("Mozambique", "MOZ");
        countryCodes.put("Mauritania", "MRT");
        countryCodes.put("Montserrat", "MSR");
        countryCodes.put("Martinique", "MTQ");
        countryCodes.put("Mauritius", "MUS");
        countryCodes.put("Malawi", "MWI");
        countryCodes.put("Malaysia", "MYS");
        countryCodes.put("Mayotte", "MYT");
        countryCodes.put("Namibia", "NAM");
        countryCodes.put("New Caledonia", "NCL");
        countryCodes.put("Niger", "NER");
        countryCodes.put("Norfolk Island", "NFK");
        countryCodes.put("Nigeria", "NGA");
        countryCodes.put("Nicaragua", "NIC");
        countryCodes.put("Niue", "NIU");
        countryCodes.put("Netherlands", "NLD");
        countryCodes.put("Norway", "NOR");
        countryCodes.put("Nepal", "NPL");
        countryCodes.put("Nauru", "NRU");
        countryCodes.put("New Zealand", "NZL");
        countryCodes.put("Oman", "OMN");
        countryCodes.put("Pakistan", "PAK");
        countryCodes.put("Panama", "PAN");
        countryCodes.put("Pitcairn", "PCN");
        countryCodes.put("Peru", "PER");
        countryCodes.put("Philippines", "PHL");
        countryCodes.put("Palau", "PLW");
        countryCodes.put("Papua New Guinea", "PNG");
        countryCodes.put("Poland", "POL");
        countryCodes.put("Puerto Rico", "PRI");
        countryCodes.put("Korea (Democratic People's Republic of)", "PRK");
        countryCodes.put("Portugal", "PRT");
        countryCodes.put("Paraguay", "PRY");
        countryCodes.put("Palestine, State of", "PSE");
        countryCodes.put("French Polynesia", "PYF");
        countryCodes.put("Qatar", "QAT");
        countryCodes.put("Réunion", "REU");
        countryCodes.put("Romania", "ROU");
        countryCodes.put("Russian Federation", "RUS");
        countryCodes.put("Rwanda", "RWA");
        countryCodes.put("Saudi Arabia", "SAU");
        countryCodes.put("Sudan", "SDN");
        countryCodes.put("Senegal", "SEN");
        countryCodes.put("Singapore", "SGP");
        countryCodes.put("South Georgia and the South Sandwich Islands", "SGS");
        countryCodes.put("Saint Helena, Ascension and Tristan da Cunha", "SHN");
        countryCodes.put("Svalbard and Jan Mayen", "SJM");
        countryCodes.put("Solomon Islands", "SLB");
        countryCodes.put("Sierra Leone", "SLE");
        countryCodes.put("El Salvador", "SLV");
        countryCodes.put("San Marino", "SMR");
        countryCodes.put("Somalia", "SOM");
        countryCodes.put("Saint Pierre and Miquelon", "SPM");
        countryCodes.put("Serbia", "SRB");
        countryCodes.put("South Sudan", "SSD");
        countryCodes.put("Sao Tome and Principe", "STP");
        countryCodes.put("Suriname", "SUR");
        countryCodes.put("Slovakia", "SVK");
        countryCodes.put("Slovenia", "SVN");
        countryCodes.put("Sweden", "SWE");
        countryCodes.put("Eswatini", "SWZ");
        countryCodes.put("Sint Maarten (Dutch part)", "SXM");
        countryCodes.put("Seychelles", "SYC");
        countryCodes.put("Syrian Arab Republic", "SYR");
        countryCodes.put("Turks and Caicos Islands", "TCA");
        countryCodes.put("Chad", "TCD");
        countryCodes.put("Togo", "TGO");
        countryCodes.put("Thailand", "THA");
        countryCodes.put("Tajikistan", "TJK");
        countryCodes.put("Tokelau", "TKL");
        countryCodes.put("Turkmenistan", "TKM");
        countryCodes.put("Timor-Leste", "TLS");
        countryCodes.put("Tonga", "TON");
        countryCodes.put("Trinidad and Tobago", "TTO");
        countryCodes.put("Tunisia", "TUN");
        countryCodes.put("Turkey", "TUR");
        countryCodes.put("Tuvalu", "TUV");
        countryCodes.put("Taiwan, Province of China", "TWN");
        countryCodes.put("Tanzania, United Republic of", "TZA");
        countryCodes.put("Uganda", "UGA");
        countryCodes.put("Ukraine", "UKR");
        countryCodes.put("United States Minor Outlying Islands", "UMI");
        countryCodes.put("Uruguay", "URY");
        countryCodes.put("United States of America", "USA");
        countryCodes.put("Uzbekistan", "UZB");
        countryCodes.put("Holy See", "VAT");
        countryCodes.put("Saint Vincent and the Grenadines", "VCT");
        countryCodes.put("Venezuela (Bolivarian Republic of)", "VEN");
        countryCodes.put("Virgin Islands (British)", "VGB");
        countryCodes.put("Virgin Islands (U.S.)", "VIR");
        countryCodes.put("Viet Nam", "VNM");
        countryCodes.put("Vanuatu", "VUT");
        countryCodes.put("Wallis and Futuna", "WLF");
        countryCodes.put("Samoa", "WSM");
        countryCodes.put("Yemen", "YEM");
        countryCodes.put("South Africa", "ZAF");
        countryCodes.put("Zambia", "ZMB");
        countryCodes.put("Zimbabwe", "ZWE");
    }
}
